/* ========================================
   Service Database
   ======================================== */

const SERVICE_DB = {
  // ---------- Databases ----------
  postgresql: {
    name: "PostgreSQL",
    category: "Databases",
    image: "postgres",
    defaultTag: "16-alpine",
    tags: ["16-alpine", "15-alpine", "14-alpine", "13-alpine"],
    defaultPort: "5432:5432",
    hostPort: 5432,
    containerPort: 5432,
    env: {
      POSTGRES_USER: "postgres",
      POSTGRES_PASSWORD: "changeme",
      POSTGRES_DB: "app",
    },
    volumes: ["pgdata:/var/lib/postgresql/data"],
    volumeDefs: { pgdata: {} },
    healthcheck: {
      test: '["CMD-SHELL", "pg_isready -U postgres"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: true,
  },

  mysql: {
    name: "MySQL",
    category: "Databases",
    image: "mysql",
    defaultTag: "8.0",
    tags: ["8.0", "8.4", "5.7"],
    defaultPort: "3306:3306",
    hostPort: 3306,
    containerPort: 3306,
    env: {
      MYSQL_ROOT_PASSWORD: "changeme",
      MYSQL_DATABASE: "app",
      MYSQL_USER: "app",
      MYSQL_PASSWORD: "changeme",
    },
    volumes: ["mysqldata:/var/lib/mysql"],
    volumeDefs: { mysqldata: {} },
    healthcheck: {
      test: '["CMD", "mysqladmin", "ping", "-h", "localhost"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: true,
  },

  mariadb: {
    name: "MariaDB",
    category: "Databases",
    image: "mariadb",
    defaultTag: "11",
    tags: ["11", "10.11", "10.6"],
    defaultPort: "3306:3306",
    hostPort: 3306,
    containerPort: 3306,
    env: {
      MARIADB_ROOT_PASSWORD: "changeme",
      MARIADB_DATABASE: "app",
      MARIADB_USER: "app",
      MARIADB_PASSWORD: "changeme",
    },
    volumes: ["mariadbdata:/var/lib/mysql"],
    volumeDefs: { mariadbdata: {} },
    healthcheck: {
      test: '["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: true,
  },

  mongodb: {
    name: "MongoDB",
    category: "Databases",
    image: "mongo",
    defaultTag: "7",
    tags: ["7", "6", "5"],
    defaultPort: "27017:27017",
    hostPort: 27017,
    containerPort: 27017,
    env: {
      MONGO_INITDB_ROOT_USERNAME: "root",
      MONGO_INITDB_ROOT_PASSWORD: "changeme",
    },
    volumes: ["mongodata:/data/db"],
    volumeDefs: { mongodata: {} },
    healthcheck: {
      test: '["CMD", "mongosh", "--eval", "db.adminCommand(\'ping\')"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: true,
  },

  redis: {
    name: "Redis",
    category: "Databases",
    image: "redis",
    defaultTag: "7-alpine",
    tags: ["7-alpine", "6-alpine"],
    defaultPort: "6379:6379",
    hostPort: 6379,
    containerPort: 6379,
    env: {},
    volumes: ["redisdata:/data"],
    volumeDefs: { redisdata: {} },
    healthcheck: {
      test: '["CMD", "redis-cli", "ping"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: false,
  },

  memcached: {
    name: "Memcached",
    category: "Databases",
    image: "memcached",
    defaultTag: "1.6-alpine",
    tags: ["1.6-alpine"],
    defaultPort: "11211:11211",
    hostPort: 11211,
    containerPort: 11211,
    env: {},
    volumes: [],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD-SHELL", "echo stats | nc localhost 11211"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: false,
  },

  elasticsearch: {
    name: "Elasticsearch",
    category: "Databases",
    image: "docker.elastic.co/elasticsearch/elasticsearch",
    defaultTag: "8.13.0",
    tags: ["8.13.0", "8.12.0", "7.17.18"],
    defaultPort: "9200:9200",
    hostPort: 9200,
    containerPort: 9200,
    env: {
      discovery_type: "single-node",
      "xpack.security.enabled": "false",
      "ES_JAVA_OPTS": "-Xms512m -Xmx512m",
    },
    volumes: ["esdata:/usr/share/elasticsearch/data"],
    volumeDefs: { esdata: {} },
    healthcheck: {
      test: '["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]',
      interval: "15s",
      timeout: "10s",
      retries: 5,
    },
    persistDefault: true,
  },

  // ---------- Message Queues ----------
  rabbitmq: {
    name: "RabbitMQ",
    category: "Message Queues",
    image: "rabbitmq",
    defaultTag: "3-management-alpine",
    tags: ["3-management-alpine", "3-alpine"],
    defaultPort: "5672:5672",
    hostPort: 5672,
    containerPort: 5672,
    extraPorts: ["15672:15672"],
    env: {
      RABBITMQ_DEFAULT_USER: "guest",
      RABBITMQ_DEFAULT_PASS: "guest",
    },
    volumes: ["rabbitmqdata:/var/lib/rabbitmq"],
    volumeDefs: { rabbitmqdata: {} },
    healthcheck: {
      test: '["CMD", "rabbitmq-diagnostics", "-q", "ping"]',
      interval: "15s",
      timeout: "10s",
      retries: 5,
    },
    persistDefault: false,
  },

  kafka: {
    name: "Kafka",
    category: "Message Queues",
    image: "confluentinc/cp-kafka",
    defaultTag: "7.6.0",
    tags: ["7.6.0", "7.5.0"],
    defaultPort: "9092:9092",
    hostPort: 9092,
    containerPort: 9092,
    env: {
      KAFKA_BROKER_ID: "1",
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181",
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092",
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT",
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT",
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1",
    },
    volumes: [],
    volumeDefs: {},
    depends_on: ["zookeeper"],
    companion: "zookeeper",
    healthcheck: {
      test: '["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]',
      interval: "15s",
      timeout: "10s",
      retries: 5,
    },
    persistDefault: false,
  },

  zookeeper: {
    name: "Zookeeper",
    category: "Message Queues",
    image: "confluentinc/cp-zookeeper",
    defaultTag: "7.6.0",
    tags: ["7.6.0", "7.5.0"],
    defaultPort: "2181:2181",
    hostPort: 2181,
    containerPort: 2181,
    env: {
      ZOOKEEPER_CLIENT_PORT: "2181",
      ZOOKEEPER_TICK_TIME: "2000",
    },
    volumes: [],
    volumeDefs: {},
    hidden: true,
    healthcheck: {
      test: '["CMD-SHELL", "echo ruok | nc localhost 2181"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: false,
  },

  // ---------- Web Servers ----------
  nginx: {
    name: "Nginx",
    category: "Web Servers",
    image: "nginx",
    defaultTag: "alpine",
    tags: ["alpine", "1.25-alpine", "1.24-alpine"],
    defaultPort: "80:80",
    hostPort: 80,
    containerPort: 80,
    env: {},
    volumes: ["./nginx.conf:/etc/nginx/conf.d/default.conf:ro"],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  apache: {
    name: "Apache",
    category: "Web Servers",
    image: "httpd",
    defaultTag: "2.4-alpine",
    tags: ["2.4-alpine"],
    defaultPort: "80:80",
    hostPort: 80,
    containerPort: 80,
    env: {},
    volumes: ["./htdocs:/usr/local/apache2/htdocs:ro"],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  caddy: {
    name: "Caddy",
    category: "Web Servers",
    image: "caddy",
    defaultTag: "2-alpine",
    tags: ["2-alpine"],
    defaultPort: "80:80",
    hostPort: 80,
    containerPort: 80,
    extraPorts: ["443:443"],
    env: {},
    volumes: ["./Caddyfile:/etc/caddy/Caddyfile:ro", "caddy_data:/data"],
    volumeDefs: { caddy_data: {} },
    healthcheck: {
      test: '["CMD", "caddy", "version"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  traefik: {
    name: "Traefik",
    category: "Web Servers",
    image: "traefik",
    defaultTag: "v3.0",
    tags: ["v3.0", "v2.11"],
    defaultPort: "80:80",
    hostPort: 80,
    containerPort: 80,
    extraPorts: ["8080:8080"],
    env: {},
    command: "--api.insecure=true --providers.docker=true",
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD", "traefik", "healthcheck"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  // ---------- App Runtimes ----------
  nodejs: {
    name: "Node.js",
    category: "App Runtimes",
    image: "node",
    defaultTag: "20-alpine",
    tags: ["22-alpine", "20-alpine", "18-alpine"],
    defaultPort: "3000:3000",
    hostPort: 3000,
    containerPort: 3000,
    env: {
      NODE_ENV: "production",
    },
    volumes: ["./app:/app"],
    volumeDefs: {},
    working_dir: "/app",
    command: "node index.js",
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost:3000/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  python: {
    name: "Python",
    category: "App Runtimes",
    image: "python",
    defaultTag: "3.12-slim",
    tags: ["3.12-slim", "3.11-slim", "3.10-slim"],
    defaultPort: "8000:8000",
    hostPort: 8000,
    containerPort: 8000,
    env: {
      PYTHONUNBUFFERED: "1",
    },
    volumes: ["./app:/app"],
    volumeDefs: {},
    working_dir: "/app",
    command: "python manage.py runserver 0.0.0.0:8000",
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost:8000/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  golang: {
    name: "Go",
    category: "App Runtimes",
    image: "golang",
    defaultTag: "1.22-alpine",
    tags: ["1.22-alpine", "1.21-alpine"],
    defaultPort: "8080:8080",
    hostPort: 8080,
    containerPort: 8080,
    env: {},
    volumes: ["./app:/app"],
    volumeDefs: {},
    working_dir: "/app",
    command: "go run .",
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost:8080/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  ruby: {
    name: "Ruby",
    category: "App Runtimes",
    image: "ruby",
    defaultTag: "3.3-slim",
    tags: ["3.3-slim", "3.2-slim"],
    defaultPort: "3000:3000",
    hostPort: 3000,
    containerPort: 3000,
    env: {
      RAILS_ENV: "production",
    },
    volumes: ["./app:/app"],
    volumeDefs: {},
    working_dir: "/app",
    command: "bundle exec rails server -b 0.0.0.0",
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost:3000/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  phpfpm: {
    name: "PHP-FPM",
    category: "App Runtimes",
    image: "php",
    defaultTag: "8.3-fpm-alpine",
    tags: ["8.3-fpm-alpine", "8.2-fpm-alpine", "8.1-fpm-alpine"],
    defaultPort: "9000:9000",
    hostPort: 9000,
    containerPort: 9000,
    env: {},
    volumes: ["./app:/var/www/html"],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD-SHELL", "php-fpm-healthcheck || exit 1"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  // ---------- Monitoring ----------
  prometheus: {
    name: "Prometheus",
    category: "Monitoring",
    image: "prom/prometheus",
    defaultTag: "v2.51.0",
    tags: ["v2.51.0", "v2.50.0"],
    defaultPort: "9090:9090",
    hostPort: 9090,
    containerPort: 9090,
    env: {},
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro", "promdata:/prometheus"],
    volumeDefs: { promdata: {} },
    healthcheck: {
      test: '["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: true,
  },

  grafana: {
    name: "Grafana",
    category: "Monitoring",
    image: "grafana/grafana",
    defaultTag: "10.4.0",
    tags: ["10.4.0", "10.3.0", "9.5.0"],
    defaultPort: "3001:3000",
    hostPort: 3001,
    containerPort: 3000,
    env: {
      GF_SECURITY_ADMIN_USER: "admin",
      GF_SECURITY_ADMIN_PASSWORD: "admin",
    },
    volumes: ["grafanadata:/var/lib/grafana"],
    volumeDefs: { grafanadata: {} },
    healthcheck: {
      test: '["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: true,
  },

  jaeger: {
    name: "Jaeger",
    category: "Monitoring",
    image: "jaegertracing/all-in-one",
    defaultTag: "1.55",
    tags: ["1.55", "1.54"],
    defaultPort: "16686:16686",
    hostPort: 16686,
    containerPort: 16686,
    env: {
      COLLECTOR_OTLP_ENABLED: "true",
    },
    volumes: [],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD", "wget", "--spider", "-q", "http://localhost:16686/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  // ---------- Other ----------
  minio: {
    name: "MinIO",
    category: "Other",
    image: "minio/minio",
    defaultTag: "latest",
    tags: ["latest"],
    defaultPort: "9000:9000",
    hostPort: 9000,
    containerPort: 9000,
    extraPorts: ["9001:9001"],
    env: {
      MINIO_ROOT_USER: "minioadmin",
      MINIO_ROOT_PASSWORD: "minioadmin",
    },
    command: 'server /data --console-address ":9001"',
    volumes: ["miniodata:/data"],
    volumeDefs: { miniodata: {} },
    healthcheck: {
      test: '["CMD", "mc", "ready", "local"]',
      interval: "10s",
      timeout: "5s",
      retries: 5,
    },
    persistDefault: true,
  },

  mailhog: {
    name: "Mailhog",
    category: "Other",
    image: "mailhog/mailhog",
    defaultTag: "latest",
    tags: ["latest"],
    defaultPort: "1025:1025",
    hostPort: 1025,
    containerPort: 1025,
    extraPorts: ["8025:8025"],
    env: {},
    volumes: [],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD", "wget", "--spider", "-q", "http://localhost:8025/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  adminer: {
    name: "Adminer",
    category: "Other",
    image: "adminer",
    defaultTag: "latest",
    tags: ["latest"],
    defaultPort: "8080:8080",
    hostPort: 8080,
    containerPort: 8080,
    env: {},
    volumes: [],
    volumeDefs: {},
    healthcheck: {
      test: '["CMD", "curl", "-f", "http://localhost:8080/"]',
      interval: "10s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },

  pgadmin: {
    name: "pgAdmin",
    category: "Other",
    image: "dpage/pgadmin4",
    defaultTag: "latest",
    tags: ["latest", "8.4"],
    defaultPort: "5050:80",
    hostPort: 5050,
    containerPort: 80,
    env: {
      PGADMIN_DEFAULT_EMAIL: "admin@example.com",
      PGADMIN_DEFAULT_PASSWORD: "admin",
    },
    volumes: ["pgadmindata:/var/lib/pgadmin"],
    volumeDefs: { pgadmindata: {} },
    healthcheck: {
      test: '["CMD", "wget", "--spider", "-q", "http://localhost:80/misc/ping"]',
      interval: "15s",
      timeout: "5s",
      retries: 3,
    },
    persistDefault: false,
  },
};

const PRESETS = {
  "MERN": ["mongodb", "nodejs", "nginx", "redis"],
  "LAMP": ["mysql", "apache", "phpfpm"],
  "Django + Postgres": ["postgresql", "python", "redis", "nginx"],
  "Rails + Redis + Postgres": ["postgresql", "redis", "ruby", "nginx"],
  "Node + Mongo": ["mongodb", "nodejs"],
  "WordPress": ["mysql", "nginx", "phpfpm"],
  "ELK-lite": ["elasticsearch", "grafana", "prometheus"],
};

const CATEGORY_ORDER = [
  "Databases",
  "Message Queues",
  "Web Servers",
  "App Runtimes",
  "Monitoring",
  "Other",
];
