// Exercise Database
// Each exercise has contraindication tags that map to injury types
const EXERCISES = [
  // ==================== CHEST ====================
  // Warmups
  { id: "chest_w1", name: "Arm Circles", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_labrum"], isWarmup: true, defaultSets: 1, defaultReps: "20 each direction", restSeconds: 0, notes: "Start small, gradually increase range" },
  { id: "chest_w2", name: "Band Pull-Aparts", muscleGroup: "chest", secondaryMuscles: ["shoulders", "back"], equipment: "resistance band", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Squeeze shoulder blades together" },
  { id: "chest_w3", name: "Wall Push-Ups", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["wrist_flexion", "chest_strain"], isWarmup: true, defaultSets: 1, defaultReps: "12", restSeconds: 0, notes: "Focus on controlled movement" },
  { id: "chest_w4", name: "Scapular Push-Ups", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["wrist_flexion"], isWarmup: true, defaultSets: 1, defaultReps: "10", restSeconds: 0, notes: "Protract and retract shoulder blades" },
  { id: "chest_w5", name: "Light Dumbbell Chest Flyes", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement", "chest_strain"], isWarmup: true, defaultSets: 1, defaultReps: "12", restSeconds: 0, notes: "Use very light weight, feel the stretch" },
  // Exercises
  { id: "chest_1", name: "Barbell Bench Press", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "barbell, bench", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "rotator_cuff", "wrist_flexion", "chest_strain"], isWarmup: false, defaultSets: 4, defaultReps: "8-10", restSeconds: 90, notes: "Keep shoulder blades retracted" },
  { id: "chest_2", name: "Dumbbell Bench Press", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "dumbbells, bench", type: "compound", difficulty: "beginner", contraindications: ["shoulder_impingement", "chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Neutral grip reduces shoulder stress" },
  { id: "chest_3", name: "Incline Dumbbell Press", muscleGroup: "chest", secondaryMuscles: ["shoulders", "triceps"], equipment: "dumbbells, bench", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "rotator_cuff", "overhead_press_load"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "30-degree incline targets upper chest" },
  { id: "chest_4", name: "Dumbbell Flyes", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: "dumbbells, bench", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement", "shoulder_labrum", "chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Do not go below shoulder level" },
  { id: "chest_5", name: "Cable Crossover", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: "cable machine", type: "isolation", difficulty: "intermediate", contraindications: ["chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Constant tension throughout" },
  { id: "chest_6", name: "Push-Ups", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders", "core"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["wrist_flexion", "chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Keep core tight, full range of motion" },
  { id: "chest_7", name: "Machine Chest Press", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "machine", type: "compound", difficulty: "beginner", contraindications: ["chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Good for beginners, fixed path" },
  { id: "chest_8", name: "Pec Deck Machine", muscleGroup: "chest", secondaryMuscles: [], equipment: "machine", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement", "shoulder_labrum", "chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Control the weight, squeeze at peak" },
  { id: "chest_9", name: "Decline Dumbbell Press", muscleGroup: "chest", secondaryMuscles: ["triceps"], equipment: "dumbbells, bench", type: "compound", difficulty: "intermediate", contraindications: ["chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Lower chest emphasis" },
  { id: "chest_10", name: "Svend Press", muscleGroup: "chest", secondaryMuscles: [], equipment: "weight plate", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Squeeze plates together throughout" },

  // ==================== BACK ====================
  // Warmups
  { id: "back_w1", name: "Cat-Cow Stretch", muscleGroup: "back", secondaryMuscles: ["core"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "10 each", restSeconds: 0, notes: "Slow, controlled movement" },
  { id: "back_w2", name: "Band Face Pulls", muscleGroup: "back", secondaryMuscles: ["shoulders"], equipment: "resistance band", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "External rotation at top" },
  { id: "back_w3", name: "Dead Hangs", muscleGroup: "back", secondaryMuscles: ["shoulders"], equipment: "pull-up bar", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement", "shoulder_labrum"], isWarmup: true, defaultSets: 1, defaultReps: "20-30 sec", restSeconds: 0, notes: "Decompress the spine" },
  { id: "back_w4", name: "Light Band Rows", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: "resistance band", type: "compound", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Focus on squeezing shoulder blades" },
  { id: "back_w5", name: "Thoracic Spine Rotations", muscleGroup: "back", secondaryMuscles: ["core"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "10 each side", restSeconds: 0, notes: "Open up the upper back" },
  // Exercises
  { id: "back_1", name: "Barbell Rows", muscleGroup: "back", secondaryMuscles: ["biceps", "core"], equipment: "barbell", type: "compound", difficulty: "intermediate", contraindications: ["spinal_compression", "lower_back_strain", "wrist_flexion"], isWarmup: false, defaultSets: 4, defaultReps: "8-10", restSeconds: 90, notes: "Hinge at hips, keep back flat" },
  { id: "back_2", name: "Pull-Ups", muscleGroup: "back", secondaryMuscles: ["biceps", "shoulders"], equipment: "pull-up bar", type: "compound", difficulty: "advanced", contraindications: ["shoulder_impingement", "shoulder_labrum", "rotator_cuff"], isWarmup: false, defaultSets: 4, defaultReps: "6-10", restSeconds: 120, notes: "Full range of motion" },
  { id: "back_3", name: "Lat Pulldowns", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: "cable machine", type: "compound", difficulty: "beginner", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Pull to upper chest, not behind neck" },
  { id: "back_4", name: "Seated Cable Rows", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: "cable machine", type: "compound", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Keep torso stationary" },
  { id: "back_5", name: "Dumbbell Rows", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: "dumbbell, bench", type: "compound", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "One arm at a time, brace on bench" },
  { id: "back_6", name: "T-Bar Rows", muscleGroup: "back", secondaryMuscles: ["biceps", "core"], equipment: "t-bar machine", type: "compound", difficulty: "intermediate", contraindications: ["spinal_compression", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "8-10", restSeconds: 90, notes: "Neutral grip reduces shoulder stress" },
  { id: "back_7", name: "Face Pulls", muscleGroup: "back", secondaryMuscles: ["shoulders"], equipment: "cable machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "15-20", restSeconds: 60, notes: "Great for posture and rotator cuff health" },
  { id: "back_8", name: "Straight Arm Pulldowns", muscleGroup: "back", secondaryMuscles: [], equipment: "cable machine", type: "isolation", difficulty: "intermediate", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Keep arms straight, hinge at shoulders" },
  { id: "back_9", name: "Machine Rows", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: "machine", type: "compound", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Fixed path, good for beginners" },
  { id: "back_10", name: "Rack Pulls", muscleGroup: "back", secondaryMuscles: ["core", "legs"], equipment: "barbell, rack", type: "compound", difficulty: "advanced", contraindications: ["spinal_compression", "lower_back_strain"], isWarmup: false, defaultSets: 4, defaultReps: "6-8", restSeconds: 120, notes: "Set pins at knee height" },
  { id: "back_11", name: "Reverse Flyes", muscleGroup: "back", secondaryMuscles: ["shoulders"], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Light weight, focus on contraction" },

  // ==================== SHOULDERS ====================
  // Warmups
  { id: "shoulders_w1", name: "Band Dislocates", muscleGroup: "shoulders", secondaryMuscles: [], equipment: "resistance band", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_labrum"], isWarmup: true, defaultSets: 1, defaultReps: "10", restSeconds: 0, notes: "Use wide grip, go slow" },
  { id: "shoulders_w2", name: "YTW Raises", muscleGroup: "shoulders", secondaryMuscles: ["back"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "8 each", restSeconds: 0, notes: "Light or bodyweight, activate rotator cuff" },
  { id: "shoulders_w3", name: "External Rotations", muscleGroup: "shoulders", secondaryMuscles: [], equipment: "resistance band", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15 each arm", restSeconds: 0, notes: "Elbow pinned to side" },
  { id: "shoulders_w4", name: "Shoulder Shrugs (Light)", muscleGroup: "shoulders", secondaryMuscles: ["neck"], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: ["neck_strain"], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Light weight warmup only" },
  // Exercises
  { id: "shoulders_1", name: "Overhead Press", muscleGroup: "shoulders", secondaryMuscles: ["triceps", "core"], equipment: "barbell", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "rotator_cuff", "overhead_press_load", "shoulder_labrum", "neck_strain", "spinal_compression"], isWarmup: false, defaultSets: 4, defaultReps: "6-8", restSeconds: 120, notes: "Brace core, do not lean back excessively" },
  { id: "shoulders_2", name: "Dumbbell Shoulder Press", muscleGroup: "shoulders", secondaryMuscles: ["triceps"], equipment: "dumbbells", type: "compound", difficulty: "beginner", contraindications: ["shoulder_impingement", "rotator_cuff", "overhead_press_load", "shoulder_labrum"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Neutral grip variant is easier on shoulders" },
  { id: "shoulders_3", name: "Lateral Raises", muscleGroup: "shoulders", secondaryMuscles: [], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Do not raise above shoulder height" },
  { id: "shoulders_4", name: "Front Raises", muscleGroup: "shoulders", secondaryMuscles: ["chest"], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: ["shoulder_impingement", "rotator_cuff"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Alternate arms for stability" },
  { id: "shoulders_5", name: "Reverse Pec Deck", muscleGroup: "shoulders", secondaryMuscles: ["back"], equipment: "machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Targets rear delts" },
  { id: "shoulders_6", name: "Cable Lateral Raises", muscleGroup: "shoulders", secondaryMuscles: [], equipment: "cable machine", type: "isolation", difficulty: "intermediate", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Constant tension with cable" },
  { id: "shoulders_7", name: "Arnold Press", muscleGroup: "shoulders", secondaryMuscles: ["triceps"], equipment: "dumbbells", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "rotator_cuff", "overhead_press_load", "shoulder_labrum"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Rotate palms as you press up" },
  { id: "shoulders_8", name: "Upright Rows", muscleGroup: "shoulders", secondaryMuscles: ["biceps"], equipment: "barbell", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "rotator_cuff", "wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Keep hands wide to reduce impingement risk" },
  { id: "shoulders_9", name: "Machine Shoulder Press", muscleGroup: "shoulders", secondaryMuscles: ["triceps"], equipment: "machine", type: "compound", difficulty: "beginner", contraindications: ["overhead_press_load", "shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Fixed path, safer for beginners" },
  { id: "shoulders_10", name: "Face Pulls", muscleGroup: "shoulders", secondaryMuscles: ["back"], equipment: "cable machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "15-20", restSeconds: 60, notes: "External rotate at the top" },

  // ==================== BICEPS ====================
  // Warmups
  { id: "biceps_w1", name: "Wrist Circles", muscleGroup: "biceps", secondaryMuscles: [], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15 each direction", restSeconds: 0, notes: "Loosen up wrists and forearms" },
  { id: "biceps_w2", name: "Light Band Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "resistance band", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Get blood flowing to biceps" },
  { id: "biceps_w3", name: "Arm Swings", muscleGroup: "biceps", secondaryMuscles: ["shoulders"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15 each arm", restSeconds: 0, notes: "Dynamic stretch for arms" },
  // Exercises
  { id: "biceps_1", name: "Barbell Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "barbell", type: "isolation", difficulty: "beginner", contraindications: ["wrist_flexion", "elbow_medial"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Keep elbows pinned to sides" },
  { id: "biceps_2", name: "Dumbbell Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: ["elbow_medial"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Alternate or simultaneous" },
  { id: "biceps_3", name: "Hammer Curls", muscleGroup: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbells", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Neutral grip, hits brachialis" },
  { id: "biceps_4", name: "Preacher Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "preacher bench, dumbbell", type: "isolation", difficulty: "intermediate", contraindications: ["elbow_medial", "elbow_lateral"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Full stretch at bottom, control the negative" },
  { id: "biceps_5", name: "Incline Dumbbell Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "dumbbells, bench", type: "isolation", difficulty: "intermediate", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Stretch at bottom, keep elbows back" },
  { id: "biceps_6", name: "Cable Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "cable machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Constant tension from cable" },
  { id: "biceps_7", name: "Concentration Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "dumbbell", type: "isolation", difficulty: "beginner", contraindications: ["elbow_medial"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Isolates bicep, no momentum" },
  { id: "biceps_8", name: "EZ Bar Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "EZ bar", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Angled grip reduces wrist strain" },
  { id: "biceps_9", name: "Chin-Ups", muscleGroup: "biceps", secondaryMuscles: ["back", "shoulders"], equipment: "pull-up bar", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "shoulder_labrum", "rotator_cuff"], isWarmup: false, defaultSets: 3, defaultReps: "6-10", restSeconds: 90, notes: "Underhand grip emphasizes biceps" },
  { id: "biceps_10", name: "Spider Curls", muscleGroup: "biceps", secondaryMuscles: [], equipment: "dumbbell, bench", type: "isolation", difficulty: "intermediate", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Chest on incline bench, arms hanging" },

  // ==================== TRICEPS ====================
  // Warmups
  { id: "triceps_w1", name: "Tricep Stretches", muscleGroup: "triceps", secondaryMuscles: ["shoulders"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "20 sec each arm", restSeconds: 0, notes: "Overhead stretch, gentle pressure" },
  { id: "triceps_w2", name: "Light Band Pushdowns", muscleGroup: "triceps", secondaryMuscles: [], equipment: "resistance band", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Light resistance, full extension" },
  { id: "triceps_w3", name: "Diamond Push-Up Hold", muscleGroup: "triceps", secondaryMuscles: ["chest"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["wrist_flexion"], isWarmup: true, defaultSets: 1, defaultReps: "15 sec hold", restSeconds: 0, notes: "Activate triceps and chest" },
  // Exercises
  { id: "triceps_1", name: "Close-Grip Bench Press", muscleGroup: "triceps", secondaryMuscles: ["chest", "shoulders"], equipment: "barbell, bench", type: "compound", difficulty: "intermediate", contraindications: ["wrist_flexion", "shoulder_impingement", "chest_strain"], isWarmup: false, defaultSets: 4, defaultReps: "8-10", restSeconds: 90, notes: "Hands shoulder-width apart" },
  { id: "triceps_2", name: "Tricep Pushdowns", muscleGroup: "triceps", secondaryMuscles: [], equipment: "cable machine", type: "isolation", difficulty: "beginner", contraindications: ["elbow_lateral"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Keep elbows pinned to sides" },
  { id: "triceps_3", name: "Overhead Tricep Extension", muscleGroup: "triceps", secondaryMuscles: [], equipment: "dumbbell", type: "isolation", difficulty: "beginner", contraindications: ["overhead_press_load", "shoulder_impingement", "elbow_lateral"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Lower weight behind head slowly" },
  { id: "triceps_4", name: "Skull Crushers", muscleGroup: "triceps", secondaryMuscles: [], equipment: "EZ bar, bench", type: "isolation", difficulty: "intermediate", contraindications: ["elbow_lateral", "wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Lower to forehead, keep elbows in" },
  { id: "triceps_5", name: "Diamond Push-Ups", muscleGroup: "triceps", secondaryMuscles: ["chest"], equipment: "none", type: "compound", difficulty: "intermediate", contraindications: ["wrist_flexion", "chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-15", restSeconds: 60, notes: "Hands close together under chest" },
  { id: "triceps_6", name: "Dips", muscleGroup: "triceps", secondaryMuscles: ["chest", "shoulders"], equipment: "dip bars", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement", "shoulder_labrum", "chest_strain"], isWarmup: false, defaultSets: 3, defaultReps: "8-12", restSeconds: 90, notes: "Lean forward for more chest, upright for triceps" },
  { id: "triceps_7", name: "Rope Pushdowns", muscleGroup: "triceps", secondaryMuscles: [], equipment: "cable machine, rope", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Spread rope at bottom for peak contraction" },
  { id: "triceps_8", name: "Tricep Kickbacks", muscleGroup: "triceps", secondaryMuscles: [], equipment: "dumbbell", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Keep upper arm parallel to floor" },
  { id: "triceps_9", name: "Machine Dips", muscleGroup: "triceps", secondaryMuscles: ["chest"], equipment: "machine", type: "compound", difficulty: "beginner", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 60, notes: "Assisted version of dips" },
  { id: "triceps_10", name: "Single-Arm Cable Pushdown", muscleGroup: "triceps", secondaryMuscles: [], equipment: "cable machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Focus on each arm individually" },

  // ==================== LEGS ====================
  // Warmups
  { id: "legs_w1", name: "Bodyweight Squats", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["deep_knee_flexion"], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Controlled tempo, full depth if comfortable" },
  { id: "legs_w2", name: "Leg Swings", muscleGroup: "legs", secondaryMuscles: ["hips"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15 each leg", restSeconds: 0, notes: "Forward/back and side to side" },
  { id: "legs_w3", name: "Hip Circles", muscleGroup: "legs", secondaryMuscles: ["hips"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["hip_impingement"], isWarmup: true, defaultSets: 1, defaultReps: "10 each direction", restSeconds: 0, notes: "Open up the hip joints" },
  { id: "legs_w4", name: "Walking Lunges (Bodyweight)", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["deep_knee_flexion", "ankle_instability"], isWarmup: true, defaultSets: 1, defaultReps: "10 each leg", restSeconds: 0, notes: "Light warmup pace" },
  { id: "legs_w5", name: "Glute Bridges", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "15", restSeconds: 0, notes: "Squeeze glutes at the top" },
  // Exercises
  { id: "legs_1", name: "Barbell Back Squat", muscleGroup: "legs", secondaryMuscles: ["core", "back"], equipment: "barbell, squat rack", type: "compound", difficulty: "intermediate", contraindications: ["deep_knee_flexion", "spinal_compression", "lower_back_strain"], isWarmup: false, defaultSets: 4, defaultReps: "6-8", restSeconds: 120, notes: "Keep chest up, drive through heels" },
  { id: "legs_2", name: "Romanian Deadlift", muscleGroup: "legs", secondaryMuscles: ["back", "core"], equipment: "barbell", type: "compound", difficulty: "intermediate", contraindications: ["lower_back_strain", "spinal_compression"], isWarmup: false, defaultSets: 4, defaultReps: "8-10", restSeconds: 90, notes: "Hinge at hips, slight knee bend" },
  { id: "legs_3", name: "Leg Press", muscleGroup: "legs", secondaryMuscles: [], equipment: "leg press machine", type: "compound", difficulty: "beginner", contraindications: ["deep_knee_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Do not lock knees at top" },
  { id: "legs_4", name: "Leg Curls", muscleGroup: "legs", secondaryMuscles: [], equipment: "machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Control the negative" },
  { id: "legs_5", name: "Leg Extensions", muscleGroup: "legs", secondaryMuscles: [], equipment: "machine", type: "isolation", difficulty: "beginner", contraindications: ["deep_knee_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Do not use excessive weight" },
  { id: "legs_6", name: "Bulgarian Split Squats", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "dumbbells, bench", type: "compound", difficulty: "intermediate", contraindications: ["deep_knee_flexion", "ankle_instability"], isWarmup: false, defaultSets: 3, defaultReps: "10 each leg", restSeconds: 90, notes: "Rear foot elevated on bench" },
  { id: "legs_7", name: "Calf Raises", muscleGroup: "legs", secondaryMuscles: [], equipment: "machine or step", type: "isolation", difficulty: "beginner", contraindications: ["ankle_instability"], isWarmup: false, defaultSets: 4, defaultReps: "15-20", restSeconds: 60, notes: "Full range of motion, pause at top" },
  { id: "legs_8", name: "Goblet Squats", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "dumbbell or kettlebell", type: "compound", difficulty: "beginner", contraindications: ["deep_knee_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Hold weight at chest, elbows inside knees" },
  { id: "legs_9", name: "Hip Thrusts", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "barbell, bench", type: "compound", difficulty: "intermediate", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Drive through heels, squeeze glutes" },
  { id: "legs_10", name: "Step-Ups", muscleGroup: "legs", secondaryMuscles: ["core"], equipment: "dumbbells, box", type: "compound", difficulty: "beginner", contraindications: ["ankle_instability", "deep_knee_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "10 each leg", restSeconds: 60, notes: "Drive through the front foot" },
  { id: "legs_11", name: "Seated Calf Raises", muscleGroup: "legs", secondaryMuscles: [], equipment: "machine", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "15-20", restSeconds: 60, notes: "Targets soleus muscle" },
  { id: "legs_12", name: "Hack Squat", muscleGroup: "legs", secondaryMuscles: [], equipment: "hack squat machine", type: "compound", difficulty: "intermediate", contraindications: ["deep_knee_flexion", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Feet shoulder width, press through heels" },

  // ==================== CORE ====================
  // Warmups
  { id: "core_w1", name: "Dead Bugs", muscleGroup: "core", secondaryMuscles: [], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "10 each side", restSeconds: 0, notes: "Keep lower back pressed to floor" },
  { id: "core_w2", name: "Bird Dogs", muscleGroup: "core", secondaryMuscles: ["back"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "10 each side", restSeconds: 0, notes: "Extend opposite arm and leg" },
  { id: "core_w3", name: "Pelvic Tilts", muscleGroup: "core", secondaryMuscles: [], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "12", restSeconds: 0, notes: "Flatten lower back against floor" },
  { id: "core_w4", name: "Cat-Cow Stretch", muscleGroup: "core", secondaryMuscles: ["back"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "10 each", restSeconds: 0, notes: "Warm up the spine" },
  // Exercises
  { id: "core_1", name: "Plank", muscleGroup: "core", secondaryMuscles: ["shoulders"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "30-60 sec", restSeconds: 60, notes: "Keep hips level, do not sag" },
  { id: "core_2", name: "Hanging Leg Raises", muscleGroup: "core", secondaryMuscles: ["hip flexors"], equipment: "pull-up bar", type: "isolation", difficulty: "advanced", contraindications: ["shoulder_impingement", "shoulder_labrum", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-15", restSeconds: 60, notes: "Control the swing, slow negative" },
  { id: "core_3", name: "Cable Crunches", muscleGroup: "core", secondaryMuscles: [], equipment: "cable machine", type: "isolation", difficulty: "intermediate", contraindications: ["spinal_compression", "neck_strain"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Crunch down, do not pull with arms" },
  { id: "core_4", name: "Russian Twists", muscleGroup: "core", secondaryMuscles: [], equipment: "weight plate or dumbbell", type: "isolation", difficulty: "intermediate", contraindications: ["spinal_compression", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "15 each side", restSeconds: 60, notes: "Keep feet elevated for more challenge" },
  { id: "core_5", name: "Ab Wheel Rollouts", muscleGroup: "core", secondaryMuscles: ["shoulders"], equipment: "ab wheel", type: "isolation", difficulty: "advanced", contraindications: ["lower_back_strain", "shoulder_impingement", "wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "8-12", restSeconds: 60, notes: "Engage core throughout, do not hyperextend" },
  { id: "core_6", name: "Bicycle Crunches", muscleGroup: "core", secondaryMuscles: [], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["neck_strain", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "15 each side", restSeconds: 60, notes: "Elbow to opposite knee, slow and controlled" },
  { id: "core_7", name: "Side Plank", muscleGroup: "core", secondaryMuscles: ["shoulders"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "20-30 sec each", restSeconds: 60, notes: "Stack feet or stagger for balance" },
  { id: "core_8", name: "Pallof Press", muscleGroup: "core", secondaryMuscles: [], equipment: "cable machine or band", type: "isolation", difficulty: "intermediate", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "10 each side", restSeconds: 60, notes: "Anti-rotation, resist the pull" },
  { id: "core_9", name: "Reverse Crunches", muscleGroup: "core", secondaryMuscles: [], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "15", restSeconds: 60, notes: "Lift hips off the floor" },
  { id: "core_10", name: "Mountain Climbers", muscleGroup: "core", secondaryMuscles: ["shoulders", "legs"], equipment: "none", type: "isolation", difficulty: "beginner", contraindications: ["wrist_flexion", "hip_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "20 each side", restSeconds: 60, notes: "Keep hips down, fast pace" },

  // ==================== FULL BODY ====================
  // Warmups
  { id: "full_w1", name: "Jumping Jacks", muscleGroup: "full_body", secondaryMuscles: [], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["ankle_instability", "deep_knee_flexion"], isWarmup: true, defaultSets: 1, defaultReps: "30", restSeconds: 0, notes: "Get heart rate up" },
  { id: "full_w2", name: "Inchworms", muscleGroup: "full_body", secondaryMuscles: ["core", "shoulders"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["wrist_flexion"], isWarmup: true, defaultSets: 1, defaultReps: "8", restSeconds: 0, notes: "Walk hands out to plank and back" },
  { id: "full_w3", name: "World's Greatest Stretch", muscleGroup: "full_body", secondaryMuscles: ["hips", "shoulders"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: [], isWarmup: true, defaultSets: 1, defaultReps: "5 each side", restSeconds: 0, notes: "Lunge, rotate, reach overhead" },
  { id: "full_w4", name: "High Knees", muscleGroup: "full_body", secondaryMuscles: ["legs", "core"], equipment: "none", type: "compound", difficulty: "beginner", contraindications: ["deep_knee_flexion", "ankle_instability"], isWarmup: true, defaultSets: 1, defaultReps: "20 each leg", restSeconds: 0, notes: "Pump arms, drive knees up" },
  // Exercises
  { id: "full_1", name: "Deadlift", muscleGroup: "full_body", secondaryMuscles: ["back", "legs", "core"], equipment: "barbell", type: "compound", difficulty: "intermediate", contraindications: ["spinal_compression", "lower_back_strain"], isWarmup: false, defaultSets: 4, defaultReps: "5-6", restSeconds: 120, notes: "Keep bar close to body, brace core" },
  { id: "full_2", name: "Clean and Press", muscleGroup: "full_body", secondaryMuscles: ["shoulders", "legs", "back"], equipment: "barbell", type: "compound", difficulty: "advanced", contraindications: ["spinal_compression", "lower_back_strain", "shoulder_impingement", "overhead_press_load", "wrist_flexion"], isWarmup: false, defaultSets: 4, defaultReps: "5-6", restSeconds: 120, notes: "Explosive movement, requires good form" },
  { id: "full_3", name: "Kettlebell Swings", muscleGroup: "full_body", secondaryMuscles: ["legs", "back", "core"], equipment: "kettlebell", type: "compound", difficulty: "intermediate", contraindications: ["lower_back_strain", "wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "15-20", restSeconds: 60, notes: "Hip hinge, do not squat" },
  { id: "full_4", name: "Thrusters", muscleGroup: "full_body", secondaryMuscles: ["shoulders", "legs", "core"], equipment: "dumbbells or barbell", type: "compound", difficulty: "intermediate", contraindications: ["deep_knee_flexion", "overhead_press_load", "shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "10-12", restSeconds: 90, notes: "Squat to press in one fluid motion" },
  { id: "full_5", name: "Burpees", muscleGroup: "full_body", secondaryMuscles: ["chest", "legs", "core"], equipment: "none", type: "compound", difficulty: "intermediate", contraindications: ["wrist_flexion", "deep_knee_flexion", "ankle_instability", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "10-15", restSeconds: 60, notes: "Full body conditioning" },
  { id: "full_6", name: "Turkish Get-Ups", muscleGroup: "full_body", secondaryMuscles: ["shoulders", "core", "legs"], equipment: "kettlebell", type: "compound", difficulty: "advanced", contraindications: ["shoulder_impingement", "shoulder_labrum", "wrist_flexion"], isWarmup: false, defaultSets: 3, defaultReps: "3 each side", restSeconds: 90, notes: "Slow, deliberate movement" },
  { id: "full_7", name: "Farmer's Walk", muscleGroup: "full_body", secondaryMuscles: ["core", "shoulders", "legs"], equipment: "dumbbells or kettlebells", type: "compound", difficulty: "beginner", contraindications: [], isWarmup: false, defaultSets: 3, defaultReps: "40 yards", restSeconds: 60, notes: "Grip tight, walk tall" },
  { id: "full_8", name: "Dumbbell Snatch", muscleGroup: "full_body", secondaryMuscles: ["shoulders", "legs", "back"], equipment: "dumbbell", type: "compound", difficulty: "advanced", contraindications: ["shoulder_impingement", "overhead_press_load", "wrist_flexion", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "6-8 each arm", restSeconds: 90, notes: "Explosive pull from floor to overhead" },
  { id: "full_9", name: "Battle Ropes", muscleGroup: "full_body", secondaryMuscles: ["shoulders", "core"], equipment: "battle ropes", type: "compound", difficulty: "intermediate", contraindications: ["shoulder_impingement"], isWarmup: false, defaultSets: 3, defaultReps: "30 sec", restSeconds: 60, notes: "Alternate waves or slams" },
  { id: "full_10", name: "Medicine Ball Slams", muscleGroup: "full_body", secondaryMuscles: ["core", "shoulders"], equipment: "medicine ball", type: "compound", difficulty: "beginner", contraindications: ["overhead_press_load", "lower_back_strain"], isWarmup: false, defaultSets: 3, defaultReps: "12-15", restSeconds: 60, notes: "Slam with full force, hinge to pick up" },
];

// Muscle group display labels
const MUSCLE_GROUPS = {
  chest: "Chest",
  back: "Back",
  shoulders: "Shoulders",
  biceps: "Biceps",
  triceps: "Triceps",
  legs: "Legs",
  core: "Core",
  full_body: "Full Body"
};
